### ISSUE TITLE
Automate additions of labels when userstyles are added

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/userstyles#141]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

At the time of writing, maintainers have to manually create labels for any new additions into this repository. This is an extra manual step that can be easily forgotten by any maintainer.

The `Issue Labeler` and `Pull Request Labeler` rely on labels that match the directories under `/styles/`, therefore, this should be automated. 

### Proposal

While we could go down the REST/GraphQL API approach, I believe this will be more painful as there doesn't seem to be a nice API call which can set all the labels for a repository at once. 

I believe we should leverage existing solutions built by the community, two of which are listed below:
- https://github.com/r7kamura/github-label-sync-action **(I prefer this)**
- https://github.com/marketplace/actions/label-syncer

### Acceptance Criteria

- [x] Leverage an existing GitHub Action to sync labels
	- [x] Auto-generate YAML file containing label definitions from each directory under `/styles/`
	- [ ] The `color` field should be taken from the `userstyles.yaml` configuration. 
		- **If a userstyle has the `color` field set**, the accent color should be taken from the `macchiato` palette.
		- **If a userstyle does not have the `color` field set**, we should default it to the `text` label. Or we could be fancy and somehow hash the name of the userstyle and generate a hex code based on that.

**Comment by sgoudham** [comment]
Upon further discussion, we've decided to hard code the label colour to `macchiato blue`. 

This keeps the code simple and avoids bringing in the catppuccin palette for giving labels unique colours. Additionally, it prevents us from over-engineering the solution to this problem.
