### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by uncenter** [catppuccin/userstyles#449]
*followup to #353, from https://github.com/catppuccin/userstyles/pull/353#issuecomment-1880319733*

- [x] Add guide on how to set up live reloading with Stylus, how to create a new userstyle with UserCSS on Stylus.
- [x] Document how to use SVGs as background-images (`@svg: escape('');`...).
- [x] Document how to replace images created with `<img>` tags (https://github.com/openstyles/stylus/wiki/Writing-styles#replacing-images-in-img-tags).
- [ ] Add guide on using Catwalk and taking good looking screenshots (i.e. Firefox's "Save Visible" mode for screenshots to keep everything consistent).
- [x] Document how to use `#rgbify`.
- [x] Document how to blur/censor text in preview screenshots (with Flow Circular font).

**Comment by isabelroses** [comment]
We should also document repo goals:
- [] Try to primarily theme root vars
- [] Avoid opinionated changes. i.e. `display: none`
- [] Attempt to avoid javascript generated css

**Comment by uncenter** [comment]
Add more explanation about how the `#catppuccin` mixin / the userstyle template actually works:
- https://www.sitepoint.com/a-comprehensive-introduction-to-less-mixins/
- https://lesscss.org/features/#mixins-feature

**Comment by uncenter** [comment]
Add more specific steps to https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md#userstylesyml about how to add yourself as a contributor (besides making a new port). This relates to updating the notice in the main README about becoming a maintainer.

**Comment by uncenter** [comment]
Document review process for pull requests. Quote below from myself (https://discord.com/channels/907385605422448742/1030437391607025765/1218274570943856846):

> ...for fix prs if bell approves then you are good to merge (and in fact we won't merge it for you, it's up to you to do it). however this doesn't apply to themes outside of your jurisdiction. for new themes usually bell and i both approve before merging and bell will do the merging herself, and for themes that you submit a fix for but you don't maintain it's best to wait for the original maintainer to approve as well

> for new themes we usually wait a little bit after approvals before merging (last minute fixes, leave time for additional reviews and comments, etc)
> like a day or two most of the time

**Comment by uncenter** [comment]
Somehow mention the tips and tricks page somewhere so people actually find/use it - I think it currently exists unlinked to by any other pages or the README.

**Comment by uncenter** [comment]
Consider updating the tip on themeing `<img>` elements to use the `content` property. See below: https://github.com/catppuccin/userstyles/blob/2c8d5ddf3fcefd9388cee37029c0800a43204a24/styles/minesweeper/catppuccin.user.css#L440
https://github.com/catppuccin/userstyles/blob/2c8d5ddf3fcefd9388cee37029c0800a43204a24/styles/google/catppuccin.user.css#L550

**Comment by uncenter** [comment]
- [ ] Cover how to install and use Deno, what scripts we have, etc.
