### ISSUE TITLE
Missing or outdated preview images

### ISSUE THREAD

**Issue by jn-sena** [catppuccin/userstyles#69]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

The following userstyles don't have the separate previews by flavours, or have outdated combined previews.

- [Cinny](https://github.com/catppuccin/userstyles/tree/main/styles/cinny)
- [Codeberg](https://github.com/catppuccin/userstyles/tree/main/styles/codeberg)
- [DeepL](https://github.com/catppuccin/userstyles/tree/main/styles/deepl)
- [ichi.moe](https://github.com/catppuccin/userstyles/tree/main/styles/ichi.moe)
- [Libreddit](https://github.com/catppuccin/userstyles/tree/main/styles/libreddit)

**Comment by isabelroses** [comment]
Thanks for letting us know, in terms of 
- [Libreddit](https://github.com/catppuccin/userstyles/tree/main/styles/libreddit) - which maybe shutting down
- [Codeberg](https://github.com/catppuccin/userstyles/tree/main/styles/codeberg) - which is getting a rework
For the rest i will take a look (progress tracker below).
- [ ] [Cinny](https://github.com/catppuccin/userstyles/tree/main/styles/cinny)

- [ ] [DeepL](https://github.com/catppuccin/userstyles/tree/main/styles/deepl)
- [ ] [ichi.moe](https://github.com/catppuccin/userstyles/tree/main/styles/ichi.moe)

**Comment by justTOBBI** [comment]
Hey, the Issue on Codeberg is noted. Once I started/finished the rework :)

**Comment by sgoudham** [comment]
I redid the images for `deepl` here: https://github.com/catppuccin/userstyles/commit/573b28a863e252f373462d8b691a15f6a0e914fe

Sorry for not tagging issue!

**Comment by sgoudham** [comment]
Codeberg was the last one listed here, just updated the previews for now and a new set of previews can be added with the upcoming rework.

Thanks everyone for updating these images!
